apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: dev-team-rw
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "services" "daemonsets", "replicasets", "pods", "statefulsets", "horizontalpodautoscalers", "jobs", "cronjobs", "replicationcontrollers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bradmccoy-dev
  namespace: dev
subjects:
- kind: User
  name: bradmccoydev@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-team-rw
  apiGroup: rbac.authorization.k8s.io
---


# kubectl create -f deployment.yaml 
# kubectl config delete-context gke_cdf-gitops_us-west1_cdf-gitops-dev
# gcloud auth login  (as bradmccoydev@gmail.com)
# gcloud container clusters get-credentials cdf-gitops-dev --project cdf-gitops